### ISSUE TITLE
Embed a SSH client in the administration panel

### ISSUE THREAD

**Issue by raulmarinperez** [egeoffrey/egeoffrey-gui#13]
**Describe the solution you'd like**
I'd like to be able to open a terminal window against the host where eGeoffrey is installed (onprem deployment) from the web browser (potentially in a different tab). Embedding SSHy (https://github.com/stuicey/SSHy) into egeoffrey-cli could be an option.

**Is your feature request related to a problem? **
Obviously this would be for advanced users (admins) who are playing around with eGeoffrey at a very low level; it's frustrating to jump from the web browser to a terminal window and vice versa when you're doing fine tuning stuff with eGeoffrey.

**Comment by user2684** [comment]
Looks like would require https://github.com/stuicey/wsProxy running somewhere. I couldn't find a pure JS implementation so far :-/

**Comment by user2684** [comment]
All the solutions found around are not pure JS but would require a service acting as bridge. 
The most simple solution would be for the user to fire up something like https://hub.docker.com/r/snsyzb/webssh by running
```
docker run -d -p 8080:8080 snsyzb/webssh
```
And then connect with the browser to port 8080. This will allow to connect to any SSH device.
Due to the size, the resources needed and considering most of the user should have a SSH client already, does not make much sense to include it as part of the eGeoffrey distribution. However, users can easily deploy it and using it if needed.
Thanks!
