### ISSUE TITLE
Heartbeat indicator

### ISSUE THREAD

**Issue by eporocrail** [egeoffrey/egeoffrey-gui#44]
I would like to have a "heartbeat indicator".

My aim is to create and implement a burglary alarm system. I would like to now that that system is on-line. I would like to implement that with a "heartbeat" every adjustable period.

To display this heartbeat a widget would be great with a small circle which can change colour from "no colour" (just empty circle) to "green colour". It would be activated by an incoming MQTT message. It would be green on incoming "1" and be blank on incoming "0",

Next to that it would be good if after an adjustable time period after the last "1" there would be generated an alarm that the burglary system is not on-line anymore.

**Comment by user2684** [comment]
Tell me if this can help: in a control/status widget there is a setting called "Elapsed from a different sensor". Here you can reference a differente sensor (by its id) and the elapsed since last value will be show up in the widget. For example what I have here are heartbeat sensors which are mapped to the MySensors I_PRE_SLEEP_NOTIFICATION and the "Elapsed from a different sensor" pointing to this sensor. In this way I can see if the sensor is alive or not just below the actual value of the sensor. 
Of course if I misunderstood your point let me know!

**Comment by user2684** [comment]
Added "heartbeat" widget
